name: CustomEnchants
version: ${project.version}
main: sp.yeyu.customeenchants.customenchants.CustomEnchants
authors: [YeYu]
description: Spigot Custom Enchants Plugin
website: https://github.com/ye-yu/sp-custom-enchants
commands:
  chance:
    description: To show the chance of getting the server's custom enchant in the enchantment table
    usage: /chance <enchantment name> like /showchance Insanely Boosted

  buildchance:
    description: <Dev Mode> To build custom enchantment chance on player.
    usage: /buildchance <player name> <enchantment name> [<chance percentage to add>] like /buildchance planc_ Insanely Boosted 20.5
